<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Inventory Report</title>
    <style>
        @page {
            margin: 100px 30px 80px 30px;
            size: landscape;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 9pt;
            color: #333;
        }

        header {
            position: fixed;
            top: -80px;
            left: 0;
            right: 0;
            height: 70px;
            text-align: center;
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
        }

        footer {
            position: fixed;
            bottom: -60px;
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            font-size: 8pt;
            color: #666;
        }

        .page-number:before {
            content: "Page " counter(page);
        }

        h1 {
            color: #1e40af;
            font-size: 22pt;
            margin: 0;
            font-weight: bold;
        }

        h2 {
            color: #2563eb;
            font-size: 12pt;
            margin: 15px 0 8px 0;
            border-bottom: 1px solid #ddd;
            padding-bottom: 3px;
        }

        .company-info {
            font-size: 9pt;
            color: #666;
            margin-top: 5px;
        }

        .report-meta {
            background-color: #f3f4f6;
            padding: 10px;
            border-radius: 5px;
            margin: 15px 0;
            border-left: 4px solid #2563eb;
            font-size: 9pt;
        }

        .summary-cards {
            display: table;
            width: 100%;
            margin: 15px 0;
        }

        .summary-card {
            display: table-cell;
            width: 20%;
            padding: 10px;
            text-align: center;
            border: 1px solid #ddd;
            background-color: #f9fafb;
        }

        .summary-card h3 {
            margin: 0 0 8px 0;
            font-size: 9pt;
            color: #666;
            font-weight: normal;
        }

        .summary-card .value {
            font-size: 14pt;
            font-weight: bold;
            color: #1e40af;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin: 10px 0;
            font-size: 8pt;
        }

        table.data-table thead {
            background-color: #1e40af;
            color: white;
        }

        table.data-table th {
            padding: 8px 4px;
            text-align: left;
            font-weight: bold;
        }

        table.data-table td {
            padding: 6px 4px;
            border-bottom: 1px solid #e5e7eb;
        }

        table.data-table tbody tr:nth-child(even) {
            background-color: #f9fafb;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .badge {
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 7pt;
            font-weight: bold;
            white-space: nowrap;
        }

        .badge-success {
            background-color: #dcfce7;
            color: #166534;
        }

        .badge-warning {
            background-color: #fef3c7;
            color: #92400e;
        }

        .badge-danger {
            background-color: #fee2e2;
            color: #991b1b;
        }

        .badge-secondary {
            background-color: #f3f4f6;
            color: #4b5563;
        }
    </style>
</head>

<body>
    <header>
        <h1>iPHARMAMART MANAGEMENT SYSTEM</h1>
        <div class="company-info">
            Pharmacy & Mini Mart | Inventory Report
        </div>
    </header>

    <footer>
        <div>Generated on: {{ now()->format('F d, Y h:i A') }}</div>
        <div class="page-number"></div>
    </footer>

    <main>
        <div class="report-meta">
            <strong>Report Type:</strong> Inventory Stock Report &nbsp;|&nbsp;
            <strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }} &nbsp;|&nbsp;
            <strong>Date:</strong> {{ now()->format('F d, Y') }}
            @if ($categoryId || $productType || $stockStatus)
                <br>
                <strong>Filters Applied:</strong>
                @if ($categoryId)
                    Category: {{ $categories->find($categoryId)->name ?? 'N/A' }}
                @endif
                @if ($productType)
                    | Product Type: {{ ucfirst($productType) }}
                @endif
                @if ($stockStatus)
                    | Stock Status: {{ ucfirst($stockStatus) }}
                @endif
            @endif
        </div>

        <h2>Inventory Summary</h2>
        <div class="summary-cards">
            <div class="summary-card">
                <h3>Total Products</h3>
                <div class="value">{{ number_format($totalProducts) }}</div>
            </div>
            <div class="summary-card">
                <h3>Stock Value</h3>
                <div class="value" style="font-size: 12pt;">₱{{ number_format($totalStockValue, 2) }}</div>
            </div>
            <div class="summary-card">
                <h3>Low Stock</h3>
                <div class="value" style="color: #d97706;">{{ number_format($lowStockCount) }}</div>
            </div>
            <div class="summary-card">
                <h3>Critical</h3>
                <div class="value" style="color: #dc2626;">{{ number_format($criticalStockCount) }}</div>
            </div>
            <div class="summary-card">
                <h3>Out of Stock</h3>
                <div class="value" style="color: #6b7280;">{{ number_format($outOfStockCount) }}</div>
            </div>
        </div>

        <h2>Product Inventory Details</h2>
        <table class="data-table">
            <thead>
                <tr>
                    <th style="width: 8%;">SKU</th>
                    <th style="width: 20%;">Product Name</th>
                    <th style="width: 10%;">Brand</th>
                    <th style="width: 12%;">Category</th>
                    <th class="text-center" style="width: 8%;">Shelf</th>
                    <th class="text-center" style="width: 8%;">Back</th>
                    <th class="text-center" style="width: 8%;">Total</th>
                    <th class="text-right" style="width: 10%;">Price</th>
                    <th class="text-right" style="width: 10%;">Value</th>
                    <th class="text-center" style="width: 6%;">Status</th>
                </tr>
            </thead>
            <tbody>
                @forelse($products as $product)
                    <tr>
                        <td>{{ $product->sku }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{{ $product->brand_name }}</td>
                        <td>{{ $product->category->name ?? 'N/A' }}</td>
                        <td class="text-center">{{ $product->shelf_stock }}</td>
                        <td class="text-center">{{ $product->back_stock }}</td>
                        <td class="text-center"><strong>{{ $product->total_stock }}</strong></td>
                        <td class="text-right">₱{{ number_format($product->price, 2) }}</td>
                        <td class="text-right">₱{{ number_format($product->total_stock * $product->price, 2) }}</td>
                        <td class="text-center">
                            @if ($product->total_stock == 0)
                                <span class="badge badge-secondary">Out</span>
                            @elseif($product->total_stock <= $product->stock_danger_level)
                                <span class="badge badge-danger">Critical</span>
                            @elseif($product->total_stock <= $product->low_stock_threshold)
                                <span class="badge badge-warning">Low</span>
                            @else
                                <span class="badge badge-success">OK</span>
                            @endif
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="10" class="text-center">No products found matching the specified criteria.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div style="margin-top: 30px; font-size: 8pt; color: #666;">
            <p><strong>Stock Status Legend:</strong></p>
            <ul style="margin: 5px 0; padding-left: 20px;">
                <li><strong>OK:</strong> Stock levels are adequate (above low stock threshold)</li>
                <li><strong>Low:</strong> Stock is below the low stock threshold but above danger level</li>
                <li><strong>Critical:</strong> Stock is at or below the danger level - immediate reordering required
                </li>
                <li><strong>Out:</strong> Product is completely out of stock</li>
            </ul>
            <p style="margin-top: 10px;"><strong>Note:</strong> All values are in Philippine Peso (₱). This report is
                system-generated.</p>
        </div>
    </main>
</body>

</html>
