<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>PWD Discount Report</title>
    <style>
        @page {
            margin: 100px 50px 80px 50px;
        }

        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10pt;
            color: #333;
        }

        header {
            position: fixed;
            top: -80px;
            left: 0;
            right: 0;
            height: 70px;
            text-align: center;
            border-bottom: 2px solid #7c3aed;
            padding-bottom: 10px;
        }

        footer {
            position: fixed;
            bottom: -60px;
            left: 0;
            right: 0;
            height: 50px;
            text-align: center;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            font-size: 9pt;
            color: #666;
        }

        .page-number:before {
            content: "Page " counter(page);
        }

        h1 {
            color: #6d28d9;
            font-size: 22pt;
            margin: 0;
            font-weight: bold;
        }

        h2 {
            color: #7c3aed;
            font-size: 14pt;
            margin: 20px 0 10px 0;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }

        .company-info {
            font-size: 9pt;
            color: #666;
            margin-top: 5px;
        }

        .report-meta {
            background-color: #f3e8ff;
            padding: 15px;
            border-radius: 5px;
            margin: 20px 0;
            border-left: 4px solid #7c3aed;
        }

        .report-meta table {
            width: 100%;
            border-collapse: collapse;
        }

        .report-meta td {
            padding: 5px;
            font-size: 10pt;
        }

        .report-meta td:first-child {
            font-weight: bold;
            width: 40%;
            color: #6d28d9;
        }

        .summary-cards {
            display: table;
            width: 100%;
            margin: 20px 0;
        }

        .summary-card {
            display: table-cell;
            width: 25%;
            padding: 15px;
            text-align: center;
            border: 1px solid #ddd;
            background-color: #faf5ff;
        }

        .summary-card h3 {
            margin: 0 0 10px 0;
            font-size: 10pt;
            color: #666;
            font-weight: normal;
        }

        .summary-card .value {
            font-size: 18pt;
            font-weight: bold;
            color: #6d28d9;
        }

        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
            font-size: 9pt;
        }

        table.data-table thead {
            background-color: #7c3aed;
            color: white;
        }

        table.data-table th {
            padding: 10px 5px;
            text-align: left;
            font-weight: bold;
        }

        table.data-table td {
            padding: 8px 5px;
            border-bottom: 1px solid #e5e7eb;
        }

        table.data-table tbody tr:nth-child(even) {
            background-color: #faf5ff;
        }

        .text-right {
            text-align: right;
        }

        .text-center {
            text-align: center;
        }

        .highlight-box {
            background-color: #f3e8ff;
            border: 2px solid #7c3aed;
            padding: 15px;
            margin: 20px 0;
            border-radius: 5px;
        }
    </style>
</head>

<body>
    <header>
        <h1>iPHARMAMART MANAGEMENT SYSTEM</h1>
        <div class="company-info">
            Pharmacy & Mini Mart | PWD Discount Report
        </div>
    </header>

    <footer>
        <div>Generated on: {{ now()->format('F d, Y h:i A') }}</div>
        <div class="page-number"></div>
    </footer>

    <main>
        <div class="report-meta">
            <table>
                <tr>
                    <td>Report Type:</td>
                    <td>Persons With Disability (PWD) Discount Report (20% Discount)</td>
                </tr>
                <tr>
                    <td>Report Period:</td>
                    <td>{{ \Carbon\Carbon::parse($month . '-01')->format('F Y') }}</td>
                </tr>
                <tr>
                    <td>Date Range:</td>
                    <td>{{ \Carbon\Carbon::parse($startDate)->format('F d, Y') }} to
                        {{ \Carbon\Carbon::parse($endDate)->format('F d, Y') }}</td>
                </tr>
                <tr>
                    <td>Generated By:</td>
                    <td>{{ auth()->user()->name ?? 'System' }}</td>
                </tr>
            </table>
        </div>

        <h2>Summary</h2>
        <div class="summary-cards">
            <div class="summary-card">
                <h3>Total Transactions</h3>
                <div class="value">{{ number_format($totalTransactions) }}</div>
            </div>
            <div class="summary-card">
                <h3>Original Amount</h3>
                <div class="value" style="font-size: 14pt;">₱{{ number_format($totalOriginalAmount, 2) }}</div>
            </div>
            <div class="summary-card">
                <h3>Total Discounts</h3>
                <div class="value" style="font-size: 14pt;">₱{{ number_format($totalDiscounts, 2) }}</div>
            </div>
            <div class="summary-card">
                <h3>Final Amount</h3>
                <div class="value" style="font-size: 14pt;">₱{{ number_format($totalFinalAmount, 2) }}</div>
            </div>
        </div>

        <div class="highlight-box">
            <strong>Philippine Law - RA 10754 (PWD Benefits Act)</strong><br>
            Persons with Disability (PWD) are entitled to a 20% discount on purchase of medicines, medical supplies, and
            other goods and services when they present their valid PWD ID card.
        </div>

        <h2>Detailed Transactions</h2>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Date/Time</th>
                    <th>Sale ID</th>
                    <th>PWD ID Number</th>
                    <th>Name</th>
                    <th class="text-right">Original Amount</th>
                    <th class="text-right">Discount (20%)</th>
                    <th class="text-right">Final Amount</th>
                </tr>
            </thead>
            <tbody>
                @forelse($transactions as $transaction)
                    <tr>
                        <td>{{ $transaction->created_at->format('M d, Y h:i A') }}</td>
                        <td>#{{ $transaction->sale_id }}</td>
                        <td>{{ $transaction->pwd_id_number }}</td>
                        <td>{{ $transaction->pwd_name }}</td>
                        <td class="text-right">₱{{ number_format($transaction->original_amount, 2) }}</td>
                        <td class="text-right">₱{{ number_format($transaction->discount_amount, 2) }}</td>
                        <td class="text-right"><strong>₱{{ number_format($transaction->final_amount, 2) }}</strong>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="text-center">No PWD transactions found for the specified period.</td>
                    </tr>
                @endforelse
            </tbody>
            @if ($transactions->count() > 0)
                <tfoot style="background-color: #f3e8ff; font-weight: bold;">
                    <tr>
                        <td colspan="4" class="text-right" style="padding: 10px;">TOTALS:</td>
                        <td class="text-right" style="padding: 10px;">₱{{ number_format($totalOriginalAmount, 2) }}
                        </td>
                        <td class="text-right" style="padding: 10px;">₱{{ number_format($totalDiscounts, 2) }}</td>
                        <td class="text-right" style="padding: 10px;">₱{{ number_format($totalFinalAmount, 2) }}</td>
                    </tr>
                </tfoot>
            @endif
        </table>

        <div style="margin-top: 40px; font-size: 9pt; color: #666;">
            <p><strong>Compliance Notes:</strong></p>
            <ul style="margin: 5px 0;">
                <li>All discounts are computed in accordance with RA 10754 (PWD Benefits Act)</li>
                <li>Valid PWD ID issued by the Department of Social Welfare and Development (DSWD) must be presented
                </li>
                <li>Discount applies to eligible items including medicines, medical supplies, and basic necessities</li>
                <li>All amounts are in Philippine Peso (₱)</li>
                <li>This report serves as documentation for compliance and audit purposes</li>
            </ul>
        </div>

        <div style="margin-top: 40px; border-top: 2px solid #ddd; padding-top: 20px;">
            <table style="width: 100%; font-size: 9pt;">
                <tr>
                    <td style="width: 50%; vertical-align: bottom;">
                        <div style="border-top: 1px solid #333; padding-top: 5px; margin-top: 40px;">
                            <strong>Prepared By</strong><br>
                            {{ auth()->user()->name ?? 'System Administrator' }}<br>
                            Date: {{ now()->format('F d, Y') }}
                        </div>
                    </td>
                    <td style="width: 50%; vertical-align: bottom; text-align: right;">
                        <div
                            style="border-top: 1px solid #333; padding-top: 5px; margin-top: 40px; display: inline-block; min-width: 200px;">
                            <strong>Reviewed By</strong><br>
                            Store Manager/Owner<br>
                            Date: _______________
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </main>
</body>

</html>
